# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tpBgP9ZS1Qg3d-IIcvZubEEQpDtKS5R8
"""

import numpy as np

r = np.array([2,6,9])
print (r)

t=np.array([[2,3,4],[7,8,9],[78,90,87]])
print(t)

y=np.arange(1,11,2)
print (y)

a= np.linspace(1,10,3)
print (a)

o = np.zeros([3,3])
print(o)

e = np.ones([2,3])
print(e)

"""functions : dtype,ndim,itemsize,nbytes"""



print(t.dtype)

print(t.ndim)

print(t.itemsize)

print(t.nbytes)

"""Shape manipulation functions"""

print(t.shape)

d= np.array([[2,3,4],[6,7,8]])
print(d)

print(d.shape)

d.shape=(3,2)
print(d)

r=d.reshape(2,3)
print(r)

g=np.random.random([2,3])
print(g)

print(g.flatten())

print(g.ravel())

h=g.T
print(h)

h= np.transpose(g)
print(h)

print('Hello')